### PR TITLE
feat: create nav bar

### PR DESCRIPTION
**Pull request by Tharshen2124**
image

The nav bar will pop up the hamburger menu when it reaches screens below 1024 px as it is following the intended design.

### CODE REVIEW

**Comment by JaxChoong** [comment]
theres only the top navbar for now right?

**Comment by Tharshen2124** [comment]
> theres only the top navbar for now right?

Yeah, just this, i will try my best to complete the rest of the page by today. Once merged, you can use it for your pages @JaxChoong

**Comment by JaxChoong** [comment]
bro added us as reviewers and merged it himself

**Comment by Tharshen2124** [comment]
you can't blame me that the merge button is right there in front of me :P

**Pull request merged**
